# Generated by Django 6.0.5 on 2026-05-23 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TallyObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('datatype', models.CharField(max_length=50)),
                ('is_list', models.BooleanField(default=False)),
                ('attributes', models.JSONField(default=dict)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema_registry.tallyobjecttype')),
            ],
            options={
                'unique_together': {('object_type', 'path')},
            },
        ),
    ]
